version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/logs/:/var/log/nginx/
    depends_on:
      -  php
    container_name: ${PROJECT_NAME}-nginx

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./src:/var/www/html
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - mysql
    container_name: ${PROJECT_NAME}-php

  mysql:
    image: mysql:latest
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    container_name: ${PROJECT_NAME}-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    container_name: ${PROJECT_NAME}-phpmyadmin